import { 
  addOrRemoveFrame,
  deleteManyFrames,
  deleteManyLanes,
  deleteOneTask,
  insertManyFrames,
  insertOneLane,
  insertOneOrganization,
  insertOneTask,
  insertOneUser,
  updateOneFrame,
  updateOneLane,
  updateOneOrganization,
  updateOneTask,
  updateOneUser,
  pushOneOrganizationMember,
  pushOneMemberOf,
} from "../mutations";

export default {
  addOrRemoveFrame,
  deleteManyLanes,
  deleteManyFrames,
  deleteOneTask,
  insertManyFrames,
  insertOneLane,
  insertOneOrganization,
  insertOneTask,
  insertOneUser,
  updateOneFrame,
  updateOneLane,
  updateOneOrganization,
  updateOneTask,
  updateOneUser,
  pushOneOrganizationMember,
  pushOneMemberOf
}
